site_name: e-mission Docs
nav:
- Home: 'README.md'
- 1. Install:
    - '1. Manual install': 'install/manual_install.md'
    - '2. Deploying your own server to production': 'install/deploying_your_own_server_to_production.md'
    - '3. Configuring authentication': 'install/configuring_authentication.md'
    - '4. Multi-layer stack': 'install/multi_layer_stack.md'
- 2. Use the app:
    - 'Use the-app': 'end_user.md'
- 3. Manage the service:
    - '1. Troubleshooting the app': 'troubleshooting_app_faq.md'
    - '2. Troubleshooting the server': 'troubleshooting_server_faq.md'
    - '3. Evaluation procedure': 'evaluation_procedure.md'
    - '4. Requesting data as a collaborator': 'requesting_data_as_a_collaborator.md'
- 4. Develop:
    - Tutorial:
        - 'Workshop intro': 'hands-on-overview.md'
        - 'Workshop fall 2018': 'logistics.md'
        - Small UI changes:
            - '1. Quickstart': 'quickstart.md'
            - '2. Easiest way to change text': 'easiest_way_to_change_text.md'
            - '3. Simple client changes': 'simple_client_changes.md'
            - '4. Summary and consent': 'summary_and_consent.md'
            - '5. Change trip en prompt': 'change_trip_end_prompt.md'
            - '6. Remove tabs': 'remove_tab.md'
            - '7. Changes needed when the set of tabs changes': 'changes_needed_when_the_set_of_tabs_changes.md'
            - '8. How to embed an external survey in the app': 'how_to_embed_an_external_survey_in_the_app.md'
    - Architecture:
        - '1. Data model': 'data_model.md'
        - '2. Module structure': 'module_structure.md'
        - '3. Mode inference pipeline': 'mode_inference_pipeline_design.md'
        - '4. Pipeline details': 'pipeline_details.md'
    - Front (Web/Mobile app):
        - '1. Phone module structure': 'phone_module_structure.md'
        - '2. App UI dev FAQ': 'high_level_faq.md'
        - '3. Create a new custom client': 'create_a_new_custom_client.md'
        - '4. You have a branch for you custom client, now what?': 'you_have_a_branch_for_your_custom_client_now_what.md'
        - '5. How to embed an external survey in the app': 'how_to_embed_an_external_survey_in_the_app.md'
        - '6. Accessing public heatmap and incident info': 'accessing_public_heatmap_and_incident_information.md'
    - Back (Server):
        - '1. Adding a new data type': 'adding_a_new_data_type.md'
        - '2. Supporting user inputs': 'supporting_user_inputs.md'
        - '3. Pushing surveys from server to phone': 'pushing_surveys_from_the_server_to_the_phone.md'
    - Future:
        - '1. Overview': 'overview.md'
        - '2. Privacy': 'privacy.md'
        - '3. privacy litt. review': 'differential_privacy_deep_dive_lit_review.md'
        - '4. Secure execution': 'secure_execution_options.md'
        - '5. Analysis': 'analysis.md'
        - '6. Scalability': 'scalability.md'
        - '7. Unanswered questions': 'unanswered_questions.md'
- 5. Contribute to the doc: 
        - 'Contributing': 'CONTRIBUTING.md'
        - 'Docs reorganisation' : 'migration_reason.md'

