site_name: e-mission Docs
repo_url: https://github.com/e-mission/
site_url: https://e-mission.eecs.berkeley.edu/
site_description: the documentation of e-mission, an open source personal mobility tracking software from UC Berkeley EECS lab

nav:
- Home: 'README.md'
- 1. Install:
    - '1. Manual install': 'install/manual_install.md'
    - '2. Deploying your own server to production': 'install/deploying_your_own_server_to_production.md'
    - '3. Configuring authentication': 'install/configuring_authentication.md'
    - '4. Multi-layer stack': 'install/multi_layer_stack.md'
- 2. Use:
    - 'Use the app': 'docs/end_user.md'
- 3. Manage:
    - '1. Troubleshooting the app': 'docs/troubleshooting_app_faq.md'
    - '2. Troubleshooting the server': 'docs/troubleshooting_server_faq.md'
    - '3. Evaluation procedure': 'docs/evaluation_procedure.md'
    - '4. Requesting data as a collaborator': 'docs/requesting_data_as_a_collaborator.md'
- 4. Develop:
    - Tutorial:
        - 'Workshop intro': 'docs/dev/tutorial/hands-on-overview.md'
        - 'Workshop fall 2018': 'docs/dev/tutorial/logistics.md'
        - Small UI changes:
            - '1. Quickstart': 'docs/dev/tutorial/small_ui_changes/quickstart.md'
            - '2. Easiest way to change text': 'docs/dev/tutorial/small_ui_changes/easiest_way_to_change_text.md'
            - '3. Simple client changes': 'docs/dev/tutorial/small_ui_changes/simple_client_changes.md'
            - '4. Summary and consent': 'docs/dev/tutorial/small_ui_changes/summary_and_consent.md'
            - '5. Change trip en prompt': 'docs/dev/tutorial/small_ui_changes/change_trip_end_prompt.md'
            - '6. Remove tabs': 'docs/dev/tutorial/small_ui_changes/remove_tab.md'
            - '7. Changes needed when the set of tabs changes': 'docs/dev/tutorial/small_ui_changes/changes_needed_when_the_set_of_tabs_changes.md'
            - '8. How to embed an external survey in the app': 'docs/dev/tutorial/small_ui_changes/how_to_embed_an_external_survey_in_the_app.md'
    - Architecture:
        - '1. Data model': 'docs/dev/archi/data_model.md'
        - '2. Module structure': 'docs/dev/archi/module_structure.md'
        - '3. Mode inference pipeline': 'docs/dev/archi/mode_inference_pipeline_design.md'
        - '4. Pipeline details': 'docs/dev/archi/pipeline_details.md'
    - Front (Web/Mobile app):
        - '1. Phone module structure': 'docs/dev/front/phone_module_structure.md'
        - '2. App UI dev FAQ': 'docs/dev/front/high_level_faq.md'
        - '3. Create a new custom client': 'docs/dev/front/create_a_new_custom_client.md'
        - '4. You have a branch for you custom client, now what?': 'docs/dev/front/you_have_a_branch_for_your_custom_client_now_what.md'
        - '5. How to embed an external survey in the app': 'docs/dev/front/how_to_embed_an_external_survey_in_the_app.md'
        - '6. Accessing public heatmap and incident info': 'docs/dev/front/accessing_public_heatmap_and_incident_information.md'
    - Back (Server):
        - '1. Adding a new data type': 'docs/dev/back/adding_a_new_data_type.md'
        - '2. Supporting user inputs': 'docs/dev/back/supporting_user_inputs.md'
        - '3. Pushing surveys from server to phone': 'docs/dev/back/pushing_surveys_from_the_server_to_the_phone.md'
    - Future:
        - '1. Overview': 'docs/dev/future/overview.md'
        - '2. Privacy': 'docs/dev/future/privacy.md'
        - '3. privacy litt. review': 'docs/dev/future/differential_privacy_deep_dive_lit_review.md'
        - '4. Secure execution': 'docs/dev/future/secure_execution_options.md'
        - '5. Analysis': 'docs/dev/future/analysis.md'
        - '6. Scalability': 'docs/dev/future/scalability.md'
        - '7. Unanswered questions': 'docs/dev/future/unanswered_questions.md'
- 5. Contribute to docs: 
        - 'Contributing': 'docs/contribute_to_the_doc/CONTRIBUTING.md'
        - 'Docs reorganisation' : 'ocs/contribute_to_the_doc/migration_reason.md'

